@startuml

scale 900 width



state FogHomePage {

[*] --> FrontPage
  FrontPage --> designCarport
  FrontPage --> standardCarport
  FrontPage --> fogKonto





  state CarportDesignSide{
  designCarport --> CarportDesignSide : tryk på knap
  [*]--> BestillingsFormular
  BestillingsFormular--> Bekræftelse : Udfylde formular/indsend
  }

  state CarportStandardSide {
  standardCarport --> CarportStandardSide : tryk på knap
  [*]--> OversigtStandardCarports
  OversigtStandardCarports--> CheckoutFormular : vælg/tryk på køb
  CheckoutFormular --> OrdreBekræftelse:Udfylde kunde- og betalingsInfo

}

  fogKonto --> FogKontoKunde : LogInd/kunde
  fogKonto --> FogKontoAdministrator : LogInd/administrator



}

state FogKontoAdministrator {
[*]-->OrdrerOversigt: tryk på ordrer-knap
OrdrerOversigt-->BeregningSystem :vælg ordre/tryk på beregnings-knap
BeregningSystem-->TegningOgStykliste :Udfyld data/tryk på beregn

}

state FogKontoKunde {


[*]-->OrdreStatus :tryk på knap
OrdreStatus-->StyklisteogTegning :tryk på knap

}

@enduml